"""First-run setup: probe Ollama servers, pick models per category, suggest pulls, write fleet.toml."""

from __future__ import annotations

import asyncio
import json
import re
import tomllib
import time
from pathlib import Path

from .config import config_path, is_cloud_model, normalize_model, parse_config
from .ollama_client import OllamaClient, OllamaError
from .providers import PROVIDERS, OpenAICompatibleClient

# Starting points measured on a 12 GB GPU desktop and a CPU-only laptop (September 2026). They are only
# suggestions: the benchmark decides what gets used, and `bench --explore` evaluates anything installed.
CATALOG = [
    {"model": "qwen2.5-coder:14b", "size_gb": 9.0, "hardware": "GPU with 10+ GB VRAM",
     "for": ["complex", "code", "tests", "scripts", "build"],
     "measured": "100% on complex and tests at ~49 tok/s on a 12 GB GPU (num_ctx 8192)"},
    {"model": "qwen3-coder:30b", "size_gb": 18.6, "hardware": "GPU with 8+ GB VRAM and 32 GB RAM (MoE, runs partly offloaded)",
     "for": ["code", "complex"], "measured": "best on the code task, ~22 tok/s with half of it in VRAM"},
    {"model": "qwen3:8b", "size_gb": 5.2, "hardware": "GPU with 6+ GB VRAM",
     "for": ["docs", "general"], "measured": "100% on docs and extraction at ~80 tok/s"},
    {"model": "qwen2.5-coder:7b", "size_gb": 4.7, "hardware": "any machine, CPU-only is fine with 16 GB RAM",
     "for": ["scripts", "build", "docs"], "measured": "~8 tok/s on a laptop CPU; weak at writing tests"},
    {"model": "qwen2.5-coder:3b", "size_gb": 1.9, "hardware": "any machine, CPU-only is fine",
     "for": ["docs", "scripts", "general"], "measured": "~15 tok/s on a laptop CPU; good for docs"},
]

HEADER = [
    "# routeai configuration - generated by setup; tune it after running a benchmark.",
    "[fleet]",
    'routing = "priority"        # priority | fastest',
    "auto_pull = false            # pull configured models that are missing on a node",
    "allow_cloud_models = false   # ':cloud' models would send your code outside your network",
    "explore_rate = 0.1",
    "",
]


def parse_spec(spec: str) -> tuple[str, str]:
    """NAME=http://host:11434, or NAME=ssh://user@host[:port] / NAME=ssh://alias for a machine reached through SSH."""
    name, _, url = spec.partition("=")
    url = url.strip().rstrip("/")
    if name and url.lower().startswith("ssh://"):
        from .sshtunnel import parse_target
        parse_target(url)  # raises ValueError with the reason
        return name.strip(), url
    if not name or not url.startswith(("http://", "https://")):
        raise ValueError(f"expected NAME=URL (e.g. gpu=http://192.168.1.13:11434 or gpu=ssh://me@server), got {spec!r}")
    return name.strip(), url


def size_b(info: dict) -> float:
    m = re.match(r"([\d.]+)\s*([BM])", str(info.get("details", {}).get("parameter_size", "")))
    if not m:
        return 0.0
    return float(m.group(1)) / (1000 if m.group(2) == "M" else 1)


def suggest_models(installed: list[dict]) -> dict[str, list[str]]:
    """Pick installed chat models per category: coder models for code work, general models for prose."""
    chat = [m for m in installed if "completion" in m.get("capabilities", ["completion"])
            and not is_cloud_model(m["name"]) and not (m.get("remote_host") or m.get("remote_model"))
            and size_b(m) >= 1.0]
    coders = sorted((m for m in chat if "coder" in m["name"].lower()), key=size_b, reverse=True)
    general = sorted((m for m in chat if "coder" not in m["name"].lower()), key=size_b, reverse=True)

    def pick(pool, max_b, count=1):
        return [m["name"] for m in pool if size_b(m) <= max_b][:count]

    code = pick(coders, 16) or pick(general, 16)
    models = {
        "complex": pick(coders, 40, 2) or code,
        "code": code, "tests": code, "scripts": code, "build": code,
        "docs": pick(general, 10) or code,
        "general": pick(general, 10) or code,
    }
    return {k: v for k, v in models.items() if v}


def suggested_pulls(installed: list[dict]) -> list[dict]:
    have = {normalize_model(m["name"]).lower() for m in installed}
    return [c for c in CATALOG if normalize_model(c["model"]).lower() not in have]


async def probe(name: str, url: str, node_type: str = "ollama", api_key_env: str | None = None,
                ssh_key: str | None = None, remote_port: int = 11434) -> dict:
    """Ask a machine or a provider what it can do. Providers list hundreds of models: we only report them."""
    remote = node_type != "ollama"
    base = {"name": name, "url": url, "type": node_type, "api_key_env": api_key_env}
    if url.lower().startswith("ssh://") and not remote:
        from .sshtunnel import SshOllamaClient, tunnel_for
        ssh = url[6:]
        base.update(ssh=ssh, ssh_key=ssh_key, remote_port=remote_port)
        client = SshOllamaClient(tunnel_for(name, ssh, remote_port, ssh_key), timeout=15)
    else:
        client = OpenAICompatibleClient(url, api_key_env, timeout=20) if remote else OllamaClient(url, timeout=10)
    try:
        version = await client.version()
        installed = await client.tags()
    except OllamaError as exc:
        return {**base, "reachable": False, "error": str(exc), "installed": [], "models": {},
                "suggested_pulls": []}
    names = [m["name"] for m in installed]
    if remote:  # the user picks which models to use; nothing is installed or downloaded
        return {**base, "reachable": True, "version": version, "installed": names[:60],
                "models": {}, "suggested_pulls": [], "available_models": len(names)}
    return {**base, "reachable": True, "version": version, "installed": names,
            "models": suggest_models(installed), "suggested_pulls": suggested_pulls(installed)}


def render(nodes: list[dict]) -> str:
    lines = list(HEADER)
    for n in nodes:
        remote = n.get("type", "ollama") != "ollama"
        lines += ["[[nodes]]", f"name = {json.dumps(n['name'])}"]
        if n.get("ssh"):
            lines.append(f"ssh = {json.dumps(n['ssh'])}          # Ollama reached through an SSH tunnel")
            if n.get("ssh_key"):
                lines.append(f"ssh_key = {json.dumps(n['ssh_key'])}")
            if int(n.get("remote_port", 11434)) != 11434:
                lines.append(f"remote_port = {int(n['remote_port'])}")
        else:
            lines.append(f"url = {json.dumps(n['url'])}")
        if remote:
            lines += [f'type = {json.dumps(n.get("type", "openai"))}',
                      f'api_key_env = {json.dumps(n.get("api_key_env") or "")}'
                      "   # the key itself lives in your environment, never here",
                      f'send_files = {"true" if n.get("send_files") else "false"}'
                      "    # may this project's files leave your machine?"]
        lines += ['tier = "auto"          # heavy | light | auto (decided by the benchmark)',
                  f"max_parallel = {n.get('max_parallel', 2 if remote else 1)}",
                  f"num_ctx = {n.get('num_ctx', 32768 if remote else 8192)}"]
        if not remote:
            lines.append('keep_alive = "30m"')
        if not n["reachable"]:
            if remote:
                hint = "check the key in $" + (n.get("api_key_env") or "?") + " and the base URL"
            elif n.get("ssh"):
                hint = f"run `routeai ssh-check {n['name']}` to see which stage fails"
            else:
                hint = "start Ollama there with OLLAMA_HOST=0.0.0.0 and allow port 11434 on your LAN"
            lines.append(f"# UNREACHABLE when generated ({n.get('error', '')[:120]}): {hint}")
        cost = n.get("cost") or {}
        if remote:
            lines += ["", "[nodes.cost]   # USD per million tokens; 0 = free tier",
                      f"input = {float(cost.get('input', 0.0))}", f"output = {float(cost.get('output', 0.0))}"]
        limits = {k: v for k, v in (n.get("limits") or {}).items() if v}
        if limits:
            lines += ["", "[nodes.limits]   # the router stops using this node when a limit is reached"]
            lines += [f"{k} = {v}" for k, v in limits.items()]
        lines += ["", "[nodes.models]"]
        if n["models"]:
            lines += [f"{cat} = {json.dumps(names)}" for cat, names in n["models"].items()]
        elif remote:
            lines.append("# choose the models for this provider, e.g.: docs = [\"gemini-2.5-flash\"]")
        else:
            lines.append("# no chat models found yet, e.g.: ollama pull qwen2.5-coder:7b")
        lines.append("")
    return "\n".join(lines)


async def generate(specs: list[tuple]) -> tuple[str, list[dict]]:
    """specs: (name, url) or (name, url, extra) where extra carries an SSH node's ssh_key and remote_port."""
    nodes = list(await asyncio.gather(*(probe(s[0], s[1], **(s[2] if len(s) > 2 else {})) for s in specs)))
    return render(nodes), nodes


def write_config(text: str, overwrite: bool = False) -> tuple[Path, Path | None]:
    """Write fleet.toml; an existing file is kept as fleet.toml.bak-<timestamp>."""
    path = config_path()
    backup = None
    if path.exists():
        if not overwrite:
            raise FileExistsError(str(path))
        backup = path.with_name(f"fleet.toml.bak-{time.strftime('%Y%m%d-%H%M%S')}")
        path.replace(backup)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path, backup


# -- editing an existing configuration -------------------------------------------------
# Surgical text edits: adding or removing one machine must not touch the comments and the
# hand-tuned settings of the others.

_NODE_HEADER = re.compile(r"^\[\[nodes\]\]\s*$", re.M)


def node_blocks(text: str) -> list[tuple[str, int, int]]:
    """(name, start, end) of every [[nodes]] block, including its [nodes.*] subtables."""
    blocks = []
    for header in _NODE_HEADER.finditer(text):
        start, end = header.start(), len(text)
        for line in re.finditer(r"^\[", text[header.end():], re.M):
            pos = header.end() + line.start()
            if text[pos:].startswith("[nodes."):
                continue
            end = pos
            break
        name = re.search(r'^name\s*=\s*"([^"]+)"', text[start:end], re.M)
        blocks.append((name.group(1) if name else "", start, end))
    return blocks


def set_node_option(text: str, name: str, key: str, value) -> str:
    literal = ("true" if value else "false") if isinstance(value, bool) else json.dumps(value)
    for node_name, start, end in node_blocks(text):
        if node_name != name:
            continue
        block = text[start:end]
        if re.search(rf"^{re.escape(key)}\s*=", block, re.M):
            block = re.sub(rf"^{re.escape(key)}\s*=.*$", f"{key} = {literal}", block, count=1, flags=re.M)
        else:
            sub = re.search(r"^\[nodes\.", block, re.M)
            head, tail = (block[:sub.start()], block[sub.start():]) if sub else (block, "")
            block = head.rstrip("\n") + f"\n{key} = {literal}\n" + (f"\n{tail}" if tail else "\n")
        return text[:start] + block + text[end:]
    raise ValueError(f"no node named {name!r} in the configuration")


def drop_node_option(text: str, name: str, key: str) -> str:
    for node_name, start, end in node_blocks(text):
        if node_name == name:
            block = re.sub(rf"^{re.escape(key)}\s*=.*\n?", "", text[start:end], count=1, flags=re.M)
            return text[:start] + block + text[end:]
    raise ValueError(f"no node named {name!r} in the configuration")


def add_node(text: str, probed: dict, options: dict | None = None) -> str:
    if any(n == probed["name"] for n, _, _ in node_blocks(text)):
        raise ValueError(f"a node named {probed['name']!r} already exists; remove it first or pick another name")
    block = "[[nodes]]" + render([probed]).split("[[nodes]]", 1)[1]
    for key, value in (options or {}).items():
        block = set_node_option(block, probed["name"], key, value)
    return text.rstrip("\n") + "\n\n" + block.strip("\n") + "\n"


def remove_node(text: str, name: str) -> str:
    for node_name, start, end in node_blocks(text):
        if node_name == name:
            return (text[:start].rstrip("\n") + "\n\n" + text[end:].lstrip("\n")).strip("\n") + "\n"
    raise ValueError(f"no node named {name!r} in the configuration")


def load_text() -> str:
    path = config_path()
    return path.read_text(encoding="utf-8") if path.exists() else render([])


def save_text(text: str) -> tuple[Path, Path | None]:
    parse_config(tomllib.loads(text))  # never replace a working configuration with one that does not load
    return write_config(text, overwrite=True)
